apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: my-family-daybook-tls
spec:
  secretName: my-family-daybook-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: myfamilydaybook.com
  dnsNames:
    - myfamilydaybook.com
    - www.myfamilydaybook.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - myfamilydaybook.com
          - www.myfamilydaybook.com
